name: Deploy web clipper extension

on:
  push:
    branches:
      - main
    paths:
      - "apps/web-clipper/**"

  pull_request:
    paths:
      - "apps/web-clipper/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build web clipper extension

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Set up node & dependencies
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --filter web-clipper --frozen-lockfile --ignore-scripts

      - name: Build the web clipper extension
        run: |
          pnpm --filter web-clipper zip
          pnpm --filter web-clipper zip:firefox

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: web-clipper-extension
          path: apps/web-clipper/.output/*.zip
          include-hidden-files: true
          if-no-files-found: error
